name: Triggers
on: 
  push:
    branches:
      - "main*"
# workflow_dispatch
# [push] #trigger the work ]flow on every push to repository

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: feature branch push
        run: echo "main branch push"
      # - name: Manually dispacth
      #   run: echo "Manually dispacthed" # this command to excute
