name: Triggers
on: 
# if someone opend PR to main branch from any feature branch,then trigger the workflow 
  pull_request:
    type: [opened, reopened]
    branches:
      - 'releases/**'

# push:
#   branches:
#     - "main*"

# workflow_dispatch

# [push] #trigger the work ]flow on every push to repository

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: main branch push
        run: echo "main branch push"
      # - name: Manually dispacth
      #   run: echo "Manually dispacthed" # this command to excute
