
name: Contexts Demo
on: [push]

env:
  project: "roboshop"
  component: "catalogue"
  environment: "dev"
jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: print info
        run: |
          echo "${{ toJSON(github) }}" 
          echo "branch name: ${{ github.ref_name }}" 

      - name: access env variables
        run: |
          echo "Project: $project"
          echo "Component: $component"
          echo "Environment: $environment"

      - naem: Accessing Secrets
        run: |
          echo "DB User name: ${{ secrets.DB_USER }}" 
          echo "DB Password: ${{ secrets.DB_PASSWORD }}" 
