
name: Contexts Demo
on: [push]

jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: print info
        run: |
          echo "${{ toJSON(github) }}" 
          echo "branch name: ${{ github.ref_name }}" 

