
name: Contexts Demo
on: [push]

env:
  project: "roboshop"
  component: "catalogue"
  environment: "dev"
jobs:

  github-context:
    runs-on: ubuntu-latest
    outputs:
      Image-name: ${{ steps.tag.outputs.image-name }}
      Image-version: ${{ steps.tag.outputs.version }}
    steps:
      - name: print info
        run: |
          echo "${{ toJSON(github) }}" 
          echo "branch name: ${{ github.ref_name }}" 

      - name: access env variables
        run: |
          echo "Project: $project"
          echo "Component: $component"
          echo "Environment: $environment"

      - name: Accessing Secrets
        run: |
          echo "DB User name: ${{ secrets.DB_USER }}" 
          echo "DB Password: ${{ secrets.DB_PASSWORD }}" 

      - name: Accessing Variables
        run: |
          echo "DB URL: ${{ vars.DB_URL }}" 

      - name: image tags
        id: tag
        run: |
          echo "image-name=catalogue" >> $GITHUB_OUTPUT 
          echo "version=1.3.0" >> $GITHUB_OUTPUT

      - name: Accessing previous step output 
        run: |
          echo "Image name: ${{ steps.tag.outputs.image-name }}"
          echo "Image Version: ${{ steps.tag.outputs.version }}"

      # github env is used for with in the job only
      - name: github env
        run: |
          echo "Goal= get a joB" >> $GITHUB_ENV
          echo "Duration= one month" >> $GITHUB_ENV

      - name: print github env
        run: |
          echo "Goal: $Goal"
          echo "Duration: $Duration" 
  
  Deploy:
    needs: github-context # depends on above job
    runs-on: ubuntu-latest
    steps:
      - name: print github env in anther jon
        run: |
          echo "Image Name: ${{ needs.github-context.outputs.Image-name}}"
          echo "Image Version: ${{ needs.github-context.outputs.Image-version}}"
