name: conditions demo
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }} # main-workflow-main
  cancel-in-progress: true # if true present execution will be cancelled , then new trigger will happen
jobs:
  say-hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: main branch
        if: github.ref_name == "main"
        run: echo "this one execute if branch is main"

      - name: feature branch
        if: github.ref_name == "feature-*"
        run: echo "this one execute if branch is feature"
        